name: Lint and Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Use Node.js'
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: 'Cache Node.js modules'
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('package-lock.json') }}

      - name: 'Install dependencies'
        run: npm ci

      - name: 'Build application'
        run: npm run build

      - name: 'Run format check'
        run: npm run format:check

      - name: 'Run lint check'
        run: npm run lint:check

      - name: 'Run tests'
        run: npm test
